---
- name: Configure NFS server
  description: >
    Used by Hawk when configuring an NFS server.

    Each step should be run separately.
    Apply new CIB before final verification step.

    export NFS(v3/v4?) from an XFS backed file system, making use of
    fencing, lock fail-over, portblock (including the "tickle"
    functionality). Explain how to have more than one export (if that's
    feasible?)
  parameters: []
  steps:
    - name: Collect
      collect: setup collect
    - name: Validate
      validate: setup validate
    - name: Precommit
      apply: setup pre
    - name: Postcommit
      apply: setup post
